Part A – Create NumPy Arrays
Import NumPy and complete these tasks:
1.Create a 1D array from [10, 20, 30, 40, 50].
2.Create a 2D array from [[10, 20, 30], [40, 50, 60]].
3.Create a 3D array using the values 1 through 8, arranged into two 2×2 blocks.
4.Print each array and identify its data type using dtype.
5.Create an array of five zeros and an array of five ones.

In [1]:
import numpy as np
arr1 = np.array([10, 20, 30, 40, 50])
arr2 = np.array([[10, 20, 30],
                 [40, 50, 60]])
arr3 = np.array([[[1, 2],
                  [3, 4]],
                 [[5, 6],
                  [7, 8]]])
print("1D Array:")
print(arr1)
print("Data type:", arr1.dtype)
print("\n2D Array:")
print(arr2)
print("Data type:", arr2.dtype)
print("\n3D Array:")
print(arr3)
print("Data type:", arr3.dtype)
zeros = np.zeros(5)
ones = np.ones(5)
print("\nArray of zeros:")
print(zeros)
print("\nArray of ones:")
print(ones)

1D Array:
[10 20 30 40 50]
Data type: int64

2D Array:
[[10 20 30]
 [40 50 60]]
Data type: int64

3D Array:
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
Data type: int64

Array of zeros:
[0. 0. 0. 0. 0.]

Array of ones:
[1. 1. 1. 1. 1.]


Part B – Dimensions and Shape
For each array created in Part A:
6.Print ndim to identify the number of dimensions.
7.Print shape to show the size along each dimension.
8.Print size to count the total number of elements.
9.In your own words, explain the difference between ndim, shape, and size.
10.Predict the shape of a 3-row, 4-column array before running the code.

In [2]:
import numpy as np
arr1 = np.array([10, 20, 30, 40, 50])
arr2 = np.array([[10, 20, 30],
                 [40, 50, 60]])
arr3 = np.array([[[1, 2],
                  [3, 4]],
                 [[5, 6],
                  [7, 8]]])
print("1D Array")
print("ndim:", arr1.ndim)
print("shape:", arr1.shape)
print("size:", arr1.size)
print("\n2D Array")
print("ndim:", arr2.ndim)
print("shape:", arr2.shape)
print("size:", arr2.size)
print("\n3D Array")
print("ndim:", arr3.ndim)
print("shape:", arr3.shape)
print("size:", arr3.size)

1D Array
ndim: 1
shape: (5,)
size: 5

2D Array
ndim: 2
shape: (2, 3)
size: 6

3D Array
ndim: 3
shape: (2, 2, 2)
size: 8


Part C – Indexing
Use this array: marks = np.array([72, 85, 91, 66, 78, 95])
11.Print the first element and the last element.
12.Print the element at index 2.
13.Print the second-last element using negative indexing.
14.Change the value 66 to 70 and print the updated array.
15.Use a 2D array [[11, 12, 13], [21, 22, 23]] to access 22 and 13.

In [ ]:
import numpy as np
marks = np.array([72, 85, 91, 66, 78, 95])
print("First element:", marks[0])
print("Last element:", marks[-1])
print("Element at index 2:", marks[2])
print("Second-last element:", marks[-2])
marks[3] = 70
print("Updated array:", marks)
arr = np.array([[11, 12, 13],
                [21, 22, 23]])
print("Element 22:", arr[1, 1])
print("Element 13:", arr[0, 2])

First element: 72
Last element: 95
Element at index 2: 91
Second-last element: 78
Updated array: [72 85 91 70 78 95]
Element 22: 22
Element 13: 13


Part D – Slicing
Use this array: values = np.array([5, 10, 15, 20, 25, 30, 35, 40])
16.Select the first four elements.
17.Select the elements from index 2 up to, but not including, index 6.
18.Select every second element.
19.Select the last three elements.
20.For matrix = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]]), select the first two rows and the last two columns.
21.Write one sentence explaining why the stop index is not included in a slice.

In [4]:
import numpy as np
values = np.array([5, 10, 15, 20, 25, 30, 35, 40])
print("First four elements:", values[:4])
print("Index 2 to 5:", values[2:6])
print("Every second element:", values[::2])
print("Last three elements:", values[-3:])
matrix = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])
print("First two rows and last two columns:")
print(matrix[:2, -2:])
print("The stop index is excluded because Python slicing")
print("includes the start index but stops before the stop index.")

First four elements: [ 5 10 15 20]
Index 2 to 5: [15 20 25 30]
Every second element: [ 5 15 25 35]
Last three elements: [30 35 40]
First two rows and last two columns:
[[2 3]
 [5 6]]
The stop index is excluded because Python slicing
includes the start index but stops before the stop index.


Part E – Vectorized Operations
Use these arrays:
a = np.array([10, 20, 30, 40])
b = np.array([1, 2, 3, 4])
22.Calculate a + b, a - b, a * b, and a / b.
23.Add 5 to every element of a without using a loop.
24.Multiply every element of a by 3.
25.Find the elements of a that are greater than 20 using a comparison operation.
26.Use a Boolean condition to select marks greater than or equal to 80 from np.array([55, 82, 91, 67, 88]).
27.In your own words, explain what vectorized operations do.

In [5]:
import numpy as np
a = np.array([10, 20, 30, 40])
b = np.array([1, 2, 3, 4])
print("Addition:", a + b)
print("Subtraction:", a - b)
print("Multiplication:", a * b)
print("Division:", a / b)
print("Add 5:", a + 5)
print("Multiply by 3:", a * 3)
print("Greater than 20:", a[a > 20])
marks = np.array([55, 82, 91, 67, 88])
result = marks[marks >= 80]
print("Marks >= 80:", result)

Addition: [11 22 33 44]
Subtraction: [ 9 18 27 36]
Multiplication: [ 10  40  90 160]
Division: [10. 10. 10. 10.]
Add 5: [15 25 35 45]
Multiply by 3: [ 30  60  90 120]
Greater than 20: [30 40]
Marks >= 80: [82 91 88]


Part F – Debugging Practice
For each snippet, identify the problem and correct it.
Debugging Problem 1
import numpy as np
arr = np.array([10, 20, 30])
print(arr[3])
Debugging Problem 2
import numpy as np
arr = np.array([1, 2, 3, 4])
print(arr[1:10])
Debugging Problem 3
import numpy as np
a = np.array([1, 2, 3])
b = np.array([10, 20])
print(a + b)
Debugging Problem 4
import numpy as np
arr = np.array([[1, 2], [3, 4]])
print(arr[2, 0])

In [7]:
#debug 1
import numpy as np
arr = np.array([10, 20, 30])
print(arr[2])
#debug 2
import numpy as np
arr = np.array([1, 2, 3, 4])
print(arr[1:])
#debug3
import numpy as np
a = np.array([1, 2, 3])
b = np.array([10, 20, 30])
print(a + b)
#debug4
import numpy as np
arr = np.array([[1, 2], [3, 4]])
print(arr[1, 0])
OUTPUT:3

30
[2 3 4]
[11 22 33]
3


Part G – Main Hands-on Activity: Student Marks Analyzer
Create a NumPy-based program to analyze student marks. Use this data:
marks = np.array([[78, 85, 92], [66, 74, 81], [90, 88, 95], [55, 69, 72]])
Each row represents one student; each column represents a subject.
Your program should:
Print the full marks array, its dimensions, and its shape.
Print the marks of the first student.
Print the marks for the second subject for all students.
Add 5 bonus marks to every score using a vectorized operation.
Cap adjusted marks at 100 using np.minimum or an equivalent NumPy operation.
Calculate each student's average marks using an axis argument.
Find the highest mark in the full array.
Select all adjusted scores that are 80 or above.
Print results with meaningful labels.

In [6]:
import numpy as np

marks = np.array([
    [78, 85, 92],
    [66, 74, 81],
    [90, 88, 95],
    [55, 69, 72]
])

print("Marks Array:\n", marks)
print("Dimensions:", marks.ndim)
print("Shape:", marks.shape)

print("First Student Marks:", marks[0])
print("Second Subject Marks:", marks[:, 1])

adjusted_marks = np.minimum(marks + 5, 100)
print("Adjusted Marks:\n", adjusted_marks)

averages = np.mean(adjusted_marks, axis=1)
print("Student Averages:", averages)

print("Highest Mark:", np.max(marks))

print("Adjusted Scores >= 80:", adjusted_marks[adjusted_marks >= 80])

Marks Array:
 [[78 85 92]
 [66 74 81]
 [90 88 95]
 [55 69 72]]
Dimensions: 2
Shape: (4, 3)
First Student Marks: [78 85 92]
Second Subject Marks: [85 74 88 69]
Adjusted Marks:
 [[ 83  90  97]
 [ 71  79  86]
 [ 95  93 100]
 [ 60  74  77]]
Student Averages: [90.         78.66666667 96.         70.33333333]
Highest Mark: 95
Adjusted Scores >= 80: [ 83  90  97  86  95  93 100]


1. What is NumPy, and why is it useful?
Answer:NumPy (Numerical Python) is a Python library used to work with arrays and perform mathematical calculations efficiently. 
2. What is a NumPy array?
Answer: A NumPy array is a data structure used to store multiple elements in one or more dimensions.
3. What is the difference between a Python list and a NumPy array?
Answer: A Python list stores multiple items and can contain different data types, while a NumPy array stores elements efficiently and supports fast mathematical operations.
4. What do ndim, shape, size, and dtype represent?
Answer:- ndim: Number of dimensions.
 shape: Size along each dimension.
 size: Total number of elements.
 dtype: Data type of the elements. 
5. What is indexing? What is negative indexing?
Answer:Indexing: Indexing is used to access an element in an array using its position, starting from index 0.
Negative Indexing: Negative indexing is used to access elements in an array from the end, starting with index -1.
6. What is slicing?
Answer: Slicing selects a range of elements from an array using start, stop, and step values.
7. What is a vectorized operation?
Answer: A vectorized operation performs an operation on all elements of a NumPy array at once without using an explicit loop.
8. Why must arrays generally have compatible shapes for element-wise arithmetic?
Answer: Arrays must have compatible shapes for element-wise arithmetic so that their elements can be matched correctly for calculations.